query getDefects($filters: DefectDefaultFilterSet, $limit: Int, $offset: Int) {
  defects(filters: $filters, limit: $limit, offset: $offset){
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    edges {
      node {
        item
        pn
        kilometer
        meter
        side
        parameter
        location
        type
        speedLimit
        status
        name
        month
        coordinates
        id
      }
      cursor
    }
    count
    total
  }
}
